```yaml
version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
  yws:
   build: ./server
   ports:
     - '1234:1234'
   enviornment:
     - MONGO_URI=mongodb:
   depends_on: [mongo]
  client:
    build: ./client
    ports:
      - '3000:3000'
    enviornment:
      - VITE_YWS_URL=ws:
      - VITE_API_URL=http:
    depends_on: [yws]
volumes:
  mongo-data:
  ```
    
